# Generated by Django 5.0.2 on 2024-02-17 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('mini_description', models.CharField(max_length=50)),
                ('content', models.TextField()),
                ('published_date', models.DateTimeField()),
            ],
        ),
    ]
